version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: 5.0
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore "src\Api\VacationRental.Api\VacationRental.Api.csproj"
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build "src\Api\VacationRental.Api\VacationRental.Api.csproj"
      
  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -r linux-x64 --self-contained false "src\Api\VacationRental.Api\VacationRental.Api.csproj"
      
artifacts:
  files:
    - '**/*'
  base-directory: ./bin/Release/netcoreapp3.1/linux-x64/publish/
  discard-paths: no