version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: 3.1
      
  pre_build:
    commands:
      - cd "src\Api\VacationRental.Api"
      - echo Restore started on `date`
      - dotnet restore VacationRental.Api.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build VacationRental.Api.csproj
      
  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -r linux-x64 --self-contained false VacationRental.Api.csproj
      
artifacts:
  files:
    - '**/*'
  base-directory: ./bin/Release/netcoreapp3.1/linux-x64/publish/
  discard-paths: no